// Source template — committed for reference. The Angular build does NOT use
// this file; it uses environment.ts / environment.docker.ts / environment.embedded.ts /
// environment.prod.ts, which are generated by client/scripts/set-environment.js
// from per-mode .env files at the repo root and are gitignored.
//
// Run `npm run set-env` (or it runs automatically as `prebuild` / `prestart`)
// to regenerate the per-mode files after .env changes.
export const environment = {
  production: false,
  apiUrl: '/api',
  authAuthority: '',
  authClientId: '__SERVICE_KEBAB__-web',
};
