#!/usr/bin/env bash
# Copyright (c) Rivoli AI 2026. All rights reserved.
#
# sync-dep-ports.sh — generate per-mode .env files from dep registration.json.
#
# Source of truth: each Andy service's `config/registration.json` declares its
# port set per mode (dotnet, docker, embedded). This script reads the local
# service's manifest plus its dependencies' manifests and writes three flat
# .env files at the repo root, one per runtime mode:
#
#   .env.dotnet    — dotnet-mode (host dev with `dotnet run`)
#   .env.docker    — docker-mode (containerized via `docker compose`)
#   .env.embedded  — embedded-mode (bundled inside Conductor)
#
# A `.env` is also written as a copy of `.env.docker`, so `docker compose up`
# works zero-config. Use `scripts/run-dev.sh` to swap to dotnet-mode.
#
# Sibling repos default to ../<dep-name> relative to the repo root. Override
# with ANDY_SIBLING_ROOT (must be an existing directory).
#
# Required deps (every Andy service): andy-auth, andy-rbac, andy-settings.
# This is hardcoded — if your service does not need one of these, set the
# corresponding env var to an empty string after running the script.
#
# Usage:
#   ./scripts/sync-dep-ports.sh           # generate all three .env files
#   ./scripts/sync-dep-ports.sh --check   # exit non-zero if regeneration needed
#   ./scripts/sync-dep-ports.sh --help    # show help

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SIBLING_ROOT="${ANDY_SIBLING_ROOT:-$(cd "$REPO_ROOT/.." && pwd)}"
LOCAL_MANIFEST="$REPO_ROOT/config/registration.json"

DEPS=(andy-auth andy-rbac andy-settings)

usage() {
  sed -n '3,28p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
  exit 0
}

case "${1:-}" in
  -h|--help) usage ;;
esac
CHECK_MODE=0
[[ "${1:-}" == "--check" ]] && CHECK_MODE=1

command -v jq >/dev/null 2>&1 || { echo "error: jq is required" >&2; exit 2; }
[[ -f "$LOCAL_MANIFEST" ]] || { echo "error: missing $LOCAL_MANIFEST" >&2; exit 2; }
[[ -d "$SIBLING_ROOT" ]] || { echo "error: ANDY_SIBLING_ROOT does not exist: $SIBLING_ROOT" >&2; exit 2; }

read_manifest_path() {
  local dep="$1"
  local path="$SIBLING_ROOT/$dep/config/registration.json"
  [[ -f "$path" ]] || { echo "error: missing dep manifest: $path" >&2; exit 2; }
  echo "$path"
}

dep_var_prefix() {
  case "$1" in
    andy-auth)     echo "ANDY_AUTH" ;;
    andy-rbac)     echo "ANDY_RBAC" ;;
    andy-settings) echo "ANDY_SETTINGS" ;;
    *) echo "error: unknown dep $1" >&2; exit 2 ;;
  esac
}

dep_role_var() {
  # Backend env-var name on the consumer side (the .NET app).
  case "$1" in
    andy-auth)     echo "AUTHORITY" ;;
    andy-rbac)     echo "API_BASE_URL" ;;
    andy-settings) echo "API_BASE_URL" ;;
  esac
}

build_url() {
  local mode="$1" port="$2" prefix="$3"
  case "$mode" in
    dotnet)   echo "https://localhost:$port" ;;
    docker)   echo "https://host.docker.internal:$port" ;;
    embedded) echo "http://localhost:9100$prefix" ;;
  esac
}

emit_env() {
  local mode="$1"
  local out
  out="# Generated by scripts/sync-dep-ports.sh — mode: $mode.\n"
  out+="# DO NOT EDIT BY HAND. Re-run the script to refresh.\n"
  out+="ANDY_RUNTIME_MODE=$mode\n"
  out+="\n"
  out+="# --- Cross-service URLs (sourced from each dep's config/registration.json) ---\n"

  local dep prefix port_field port url role var
  for dep in "${DEPS[@]}"; do
    local manifest
    manifest="$(read_manifest_path "$dep")"
    prefix="$(jq -r '.service.embeddedProxyPrefix' "$manifest")"
    case "$mode" in
      dotnet)   port_field="dotnetHttps" ;;
      docker)   port_field="dockerHttps" ;;
      embedded) port_field="embeddedProxy" ;;
    esac
    port="$(jq -r ".service.ports.$port_field" "$manifest")"
    url="$(build_url "$mode" "$port" "$prefix")"
    role="$(dep_role_var "$dep")"
    var="$(dep_var_prefix "$dep")_${role}"
    out+="$var=$url\n"
  done

  out+="\n"
  out+="# --- This service's identity (from local config/registration.json) ---\n"
  out+="ANDY_AUTH_AUDIENCE=$(jq -r '.auth.audience' "$LOCAL_MANIFEST")\n"
  out+="ANDY_RBAC_APPLICATION_CODE=$(jq -r '.rbac.applicationCode' "$LOCAL_MANIFEST")\n"
  out+="ANDY_SETTINGS_APPLICATION_CODE=$(jq -r '.rbac.applicationCode' "$LOCAL_MANIFEST")\n"
  out+="ANDY_FRONTEND_AUTH_CLIENT_ID=$(jq -r '.auth.webClient.clientId // ""' "$LOCAL_MANIFEST")\n"

  printf "%b" "$out"
}

write_or_check() {
  local mode="$1"
  local target="$REPO_ROOT/.env.$mode"
  local content
  content="$(emit_env "$mode")"

  if (( CHECK_MODE )); then
    if [[ ! -f "$target" ]] || ! diff -q <(printf "%s" "$content") "$target" >/dev/null 2>&1; then
      echo "drift: $target needs regeneration" >&2
      return 1
    fi
    return 0
  fi

  printf "%s" "$content" > "$target"
  echo "wrote $target"
}

drift=0
for mode in dotnet docker embedded; do
  write_or_check "$mode" || drift=1
done

if (( CHECK_MODE )); then
  if (( drift )); then
    echo "Run ./scripts/sync-dep-ports.sh to regenerate." >&2
    exit 1
  fi
  echo "all .env files in sync"
  exit 0
fi

# Default .env is a copy of docker mode (compose auto-loads it on `up`).
cp "$REPO_ROOT/.env.docker" "$REPO_ROOT/.env"
echo "wrote $REPO_ROOT/.env (copy of .env.docker)"
